### ISSUE TITLE
Sometimes rocket will not change body

### ISSUE THREAD

**Issue by Arugin** [qsantos/spyce#1]
https://github.com/qsantos/spyce/blob/3c7c1ecd30cbf51c7aef7b388c646bbf2ef28832/spyce/rocket.py#L129

 self.orbit.apoapsis < satellite.orbit.periapsis does not take into account sphere of influence of sattelite. More correct one will be:
satellite.orbit.periapsis - orbit.apoapsis > satellite.sphereOfInfluence

**Comment by qsantos** [comment]
Very good catch, thanks for the report!
